;; main init.el
(add-to-list 'load-path "~/.emacs.d/lisp")
(load-file "~/.emacs.d/conf/common/init.el")
(if
 (member
  (system-name) '("rbsmith-desktop.adams.edu" "rbsmith-laptop" "ChrUbuntu" "shelob.vuser.org" "localhost" "archusb.localdomain"))
 (load-file "~/.emacs.d/conf/desktop/init.el")
 (load-file "~/.emacs.d/conf/server/init.el")
)


(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elfeed-feeds
   (quote
    (("http://feeds.feedburner.com/FootballOutsiders" nfl personal)
     ("http://nflfilms.nfl.com/feed/" nfl personal)
     ("http://espn.go.com/blog/feed?blog=afcwest" nfl personal)
     ("http://rossputin.com/blog/index.php?tempskin=_rss2" colorado politics personal)
     ("http://ariarmstrong.com/feed/" colorado politics personal)
     ("http://feeds.denverpost.com/dp-politics-local_politics" colorado politics personal)
     ("http://www.ediswatching.org/feed/" colorado edu politics personal)
     ("http://gazette.com/rss/more/government" colorado politics personal)
     ("http://www.bluecarp.com/feeds/posts/default" colorado politics personal)
     ("http://feeds.feedburner.com/MichelleMorin" colorado politics personal)
     ("http://feeds.denverpost.com/dp-news-local-schools-highered" colorado edu politics personal)
     ("http://www.cologop.org/feed/" colorado politics personal)
     ("http://www.statebillnews.com/feed/" colorado politics personal)
     ("http://www.joncaldara.com/feed/" colorado politics personal)
     ("http://coloradostatesman.com/rss.xml" colorado politics personal)
     ("http://completecolorado.com/pagetwo/feed/" colorado politics personal)
     ("http://energy.i2i.org/feed/rss/" colorado politics personal)
     ("http://www.ednewscolorado.org/feed" colorado edu politics personal)
     ("http://coloradopeakpolitics.com/feed/" colorado politics personal)
     ("http://feeds.denverpost.com/dp-politics-legislature" colorado politics personal)
     ("http://www.jsharf.com/view/?feed=rss2" colorado politics personal)
     ("http://news.google.com/news?pz=1&cf=all&ned=us&hl=en&geo=81101&output=rss" colorado personal)
     ("http://rssfeeds.9news.com/kusa-politics" colorado politics personal)
     ("http://www.daybydaycartoon.com/feed/" comics personal)
     ("http://www.bugmartini.com/feed/" comics personal)
     ("http://feeds.feedburner.com/NotInventedHere" comics personal)
     ("http://reallifecomics.com/rss.php?feed=rss2" comics personal)
     ("http://xkcd.com/rss.xml" comics personal)
     ("http://www.sheldoncomics.com/index.xml" comics personal)
     ("http://theoatmeal.com/feed/rss" comics personal)
     ("http://feeds.feedburner.com/GeekAndPoke" comics personal)
     ("http://www.evil-inc.com/feed/" comics personal)
     ("http://www.foxtrot.com/feed/" comics personal)
     ("http://feeds.feedburner.com/SchlockRSS" comics personal)
     ("http://www.dieselsweeties.com/ds-unifeed.xml" comics personal)
     ("http://feeds.feedburner.com/DuelingAnalogs" comics personal)
     ("http://feeds.feedburner.com/SuperSiblings" comics personal)
     ("http://www.drivecomic.com/index.xml" comics personal)
     ("http://feeds2.feedburner.com/wondermark" comics personal)
     ("http://starcrossedonline.com/feed/" comics personal)
     ("http://www.libertynews.com/feed/" tier1 politics personal)
     ("http://www.reason.com/news/index.xml" tier1 politics personal)
     ("http://www.eff.org/rss/updates.xml" tier1 politics tech personal)
     ("http://www.cbo.gov/publications/directors-blog/rss.xml" tier1 politics personal)
     ("http://feeds.feedburner.com/melissaclouthier/PTzm" tier1 politics personal)
     ("http://feeds.feedburner.com/hotair/main" tier1 politics personal)
     ("http://ace.mu.nu/index.rdf" tier1 politics personal)
     ("http://blog.heritage.org/feed/" tier1 politics personal)
     ("http://www.politicalmathblog.com/?feed=rss2" tier1 politics personal)
     ("http://www.downsizinggovernment.org/rss.xml" tier1 politics personal)
     ("http://feeds.feedburner.com/michellemalkin/posts" tier1 politics personal)
     ("http://feeds.feedburner.com/PerlBuzz" perl personal work)
     ("http://www.modernperlbooks.com/mt/atom.xml" perl personal work)
     ("http://chronicle.com/blogs/ticker/feed" tier2 politics edu personal)
     ("http://www.theblaze.com/stories/feed/" tier2 politics personal)
     ("http://jon.netdork.net/atom.xml" tier2 politics tech personal)
     ("http://wattsupwiththat.com/feed/" tier2 politics personal)
     ("http://feeds.feedburner.com/PajamasMedia" tier3 politics personal)
     ("http://feeds.feedburner.com/FreeBeacon" tier3 politics personal)
     ("http://recode.net/feed/" tech personal tier2)
     ("http://feeds.feedburner.com/ommalik" tech tier1 personal)
     ("http://feeds2.feedburner.com/Kvm-TheLinuxKernel-basedVirtualMachine" tech personal work)
     ("http://www.schneier.com/blog/index.rdf" tech tier1 personal work)
     ("http://fridge.ubuntu.com/node/feed" tech personal)
     ("http://cloud-mechanic.blogspot.com/feeds/posts/default" tech personal learning work)
     ("http://www.theverge.com/rss/frontpage" tech tier1 personal)
     ("http://news.google.com/news?pz=1&cf=all&ned=us&hl=en&topic=tc&output=rss" tech personal tier3)
     ("http://perlstalker.vuser.org/Scriptures/dc.rdf" lds scriptures personal)
     ("http://newsroom.lds.org/rss.xqy?a=news" lds personal)
     ("http://lds.org/tools/rss?lang=eng&uri=/church/news&location=article" lds personal)
     ("http://howardtayler.com/feed/" fun personal)
     ("http://www.bureau42.com/feed" fun personal)
     ("http://mentalfloss.com/blogs/feed/rss" fun personal)
     ("http://www.quotationspage.com/data/qotd.rss" fun personal)
     ("http://www.us-cert.gov/channels/userdocs.rdf" work security)
     ("http://adams.edu/news/rss.xml" work asu)
     ("http://blogs.adams.edu/campus/feed/" work asu)
     ("http://blogs.adams.edu/finance/feed/" work asu edu)
     ("http://feeds.feedburner.com/powershellfeed" work learning)
     ("http://www.archlinux.org/feeds/news/" work linux)
     ("http://blog.bestpractical.com/atom.xml" work apps)
     ("https://blogs.apache.org/cloudstack/feed/entries/atom" work apps)
     ("http://feeds.feedburner.com/OfficialGmailBlog" work apps google)
     ("http://blog.docker.io/feed/" work apps)
     ("http://feeds.feedburner.com/GoogleDriveBlog" work apps google)
     ("http://opennebula.org/feed/" work apps)
     ("http://pyd.io/feed/" work apps)
     ("http://feeds.feedburner.com/GoogleChromeReleases" work apps google)
     ("http://feeds.feedburner.com/GoogleAppsUpdates" work apps google)
     ("http://ceph.com/feed/" work apps)
     ("http://www.saltstack.com/salt-blog/?format=rss" work apps)
     ("http://www.google.com/appsstatus/rss/en" work google))))
)
