(setq newsticker-automatically-mark-items-as-old nil)
(setq newsticker-ticker-interval 0)
(setq newsticker-dir "~/Dropbox/newsticker/")

(setq
 newsticker-url-list
 (quote
  (
   ("Tickets" "https://helpdesk.adams.edu/NoAuth/rss/rbsmith/6ae4ea7287d1b32f/?Order=ASC%7CASC%7CASC%7CASC&OrderBy=id%7C%7C%7C&Query=(+Status+%3D+%27new%27+OR+Status+%3D+%27open%27+)+AND+(++Owner+%3D+%27rbsmith%27+OR+(++Owner+%3D+%27Nobody%27+AND+(++Queue+%3D+%27Server%27+OR+Queue+%3D+%27Account+Management%27+)+)+)" nil nil nil)
   ("SaltStack Blog" "http://saltstack.com/feed/" nil nil nil)
   ("Football Outsiders" "http://feeds.feedburner.com/FootballOutsiders" nil nil nil)
   ("NFL Films" "http://nflfilms.nfl.com/feed/" nil nil nil)
   ("ESPN - AFC West blog" "http://espn.go.com/blog/feed?blog=afcwest" nil nil nil)
   ("Rossputin" "http://rossputin.com/blog/index.php?tempskin=_rss2" nil nil nil)
   ("Ari Armstrong" "http://ariarmstrong.com/feed/" nil nil nil)
   ("Denver Post - local politics" "http://feeds.denverpost.com/dp-politics-local_politics" nil nil nil)
   ("Ed is Watching" "http://www.ediswatching.org/feed/" nil nil nil)
   ("Gazette - Government" "http://gazette.com/rss/more/government" nil nil nil)
   ("Blue Carp" "http://www.bluecarp.com/feeds/posts/default" nil nil nil)
   ("Michelle Morin" "http://feeds.feedburner.com/MichelleMorin" nil nil nil)
   ("Denver Post - Higher ed" "http://feeds.denverpost.com/dp-news-local-schools-highered" nil nil nil)
   ("CO GOP" "http://www.cologop.org/feed/" nil nil nil)
   ("State Bill Colorado" "http://www.statebillnews.com/feed/" nil nil nil)
   ("Jon Caldara" "http://www.joncaldara.com/feed/" nil nil nil)
   ("Colorado Statesman" "http://coloradostatesman.com/rss.xml" nil nil nil)
   ("Complete Colorado" "http://completecolorado.com/pagetwo/feed/" nil nil nil)
   ("i2i - Energy" "http://energy.i2i.org/feed/rss/" nil nil nil)
   ("Ed News Colorado" "http://www.ednewscolorado.org/feed" nil nil nil)
   ("Colorado Peak Politics" "http://coloradopeakpolitics.com/feed/" nil nil nil)
   ("Denver Post - legislature" "http://feeds.denverpost.com/dp-politics-legislature" nil nil nil)
   ("Jsharf" "http://www.jsharf.com/view/?feed=rss2" nil nil nil)
   ("Google News - 81101" "http://news.google.com/news?pz=1&cf=all&ned=us&hl=en&geo=81101&output=rss" nil nil nil)
   ("9news - politics" "http://rssfeeds.9news.com/kusa-politics" nil nil nil)
   ("Day by Day Cartoon" "http://www.daybydaycartoon.com/feed/" nil nil nil)
   ("Bug Martini" "http://www.bugmartini.com/feed/" nil nil nil)
   ("Not Invented Here" "http://feeds.feedburner.com/NotInventedHere" nil nil nil)
   ("Real Live Comics" "http://reallifecomics.com/rss.php?feed=rss2" nil nil nil)
   ("XKCD" "http://xkcd.com/rss.xml" nil nil nil)
   ("Sheldon" "http://www.sheldoncomics.com/index.xml" nil nil nil)
   ("The Oatmeal" "http://theoatmeal.com/feed/rss" nil nil nil)
   ("Geek and Pike" "http://feeds.feedburner.com/GeekAndPoke" nil nil nil)
   ("Evil Inc." "http://www.evil-inc.com/feed/" nil nil nil)
   ("Foxtrot" "http://www.foxtrot.com/feed/" nil nil nil)
   ("Schlock Mercenary" "http://feeds.feedburner.com/SchlockRSS" nil nil nil)
   ("Diesel Sweeties" "http://www.dieselsweeties.com/ds-unifeed.xml" nil nil nil)
   ("Dueling Analogs" "http://feeds.feedburner.com/DuelingAnalogs" nil nil nil)
   ("Super Siblings" "http://feeds.feedburner.com/SuperSiblings" nil nil nil)
   ("Drive Comic" "http://www.drivecomic.com/index.xml" nil nil nil)
   ("Wondermark" "http://feeds2.feedburner.com/wondermark" nil nil nil)
   ("Star Crossed" "http://starcrossedonline.com/feed/" nil nil nil)
   ("Liberty News" "http://www.libertynews.com/feed/" nil nil nil)
   ("Reason.com" "http://feeds.feedburner.com/reason/AllArticles" nil nil nil)
   ("EFF" "http://www.eff.org/rss/updates.xml" nil nil nil)
   ("CBO Directors blog" "http://www.cbo.gov/publications/directors-blog/rss.xml" nil nil nil)
   ("Melissa Clouthier" "http://feeds.feedburner.com/melissaclouthier/PTzm" nil nil nil)
   ("Hot Air" "http://feeds.feedburner.com/hotair/main" nil nil nil)
   ("Ace of Spades HQ" "http://ace.mu.nu/index.rdf" nil nil nil)
   ("The Foundry" "http://blog.heritage.org/feed/" nil nil nil)
   ("Political Math" "http://www.politicalmathblog.com/?feed=rss2" nil nil nil)
   ("Downsizing Government" "http://www.downsizinggovernment.org/rss.xml" nil nil nil)
   ("Michelle Malkin" "http://feeds.feedburner.com/michellemalkin/posts" nil nil nil)
   ("Perl Buzz" "http://feeds.feedburner.com/PerlBuzz" nil nil nil)
   ("Modern Perl Books" "http://www.modernperlbooks.com/mt/atom.xml" nil nil nil)
   ("Chronicle of Higher Ed" "http://chronicle.com/blogs/ticker/feed" nil nil nil)
   ("The Blaze" "http://www.theblaze.com/stories/feed/" nil nil nil)
   ("Jon Netdork" "http://jon.netdork.net/atom.xml" nil nil nil)
   ("Watts Up With That" "http://wattsupwiththat.com/feed/" nil nil nil)
   ("Pajamas Media" "http://feeds.feedburner.com/PajamasMedia" nil nil nil)
   ("Free Beacon" "http://feeds.feedburner.com/FreeBeacon" nil nil nil)
   ("Re/code" "http://recode.net/feed/" nil nil nil)
   ("Gigaom" "http://feeds.feedburner.com/ommalik" nil nil nil)
   ("Linux KVM" "http://feeds2.feedburner.com/Kvm-TheLinuxKernel-basedVirtualMachine" nil nil nil)
   ("Schneier on Security" "http://www.schneier.com/blog/index.rdf" nil nil nil)
   ("Ubuntu updates" "http://fridge.ubuntu.com/node/feed" nil nil nil)
   ("Cloud Mechaninc" "http://cloud-mechanic.blogspot.com/feeds/posts/default" nil nil nil)
   ("The Verge" "http://www.theverge.com/rss/frontpage" nil nil nil)
   ("Google News - tech" "http://news.google.com/news?pz=1&cf=all&ned=us&hl=en&topic=tc&output=rss" nil nil nil)
   ("Scriptures - D&C" "http://perlstalker.vuser.org/Scriptures/dc.rdf" nil nil nil)
   ("LDS Newsroom" "http://newsroom.lds.org/rss.xqy?a=news" nil nil nil)
   ("Church News" "http://lds.org/tools/rss?lang=eng&uri=/church/news&location=article" nil nil nil)
   ("Howard Tayler" "http://howardtayler.com/feed/" nil nil nil)
   ("Bureau 42" "http://www.bureau42.com/feed" nil nil nil)
   ("Mental Floss" "http://mentalfloss.com/blogs/feed/rss" nil nil nil)
   ("Daily Quotes" "http://www.quotationspage.com/data/qotd.rss" nil nil nil)
   ("US CERT" "http://www.us-cert.gov/channels/userdocs.rdf" nil nil nil)
   ("ASU news" "http://adams.edu/news/rss.xml" nil nil nil)
   ("ASU Events" "http://blogs.adams.edu/campus/feed/" nil nil nil)
   ("ASU Finance" "http://blogs.adams.edu/finance/feed/" nil nil nil)
   ("Powershell" "http://feeds.feedburner.com/powershellfeed" nil nil nil)
   ("Arch Linux" "http://www.archlinux.org/feeds/news/" nil nil nil)
   ("RT Blog" "http://blog.bestpractical.com/atom.xml" nil nil nil)
   ("Cloudstack blog" "https://blogs.apache.org/cloudstack/feed/entries/atom" nil nil nil)
   ("Gmail blog" "http://feeds.feedburner.com/OfficialGmailBlog" nil nil nil)
   ("Docker blog" "http://blog.docker.io/feed/" nil nil nil)
   ("Google Drive blog" "http://feeds.feedburner.com/GoogleDriveBlog" nil nil nil)
   ("OpenNebula" "http://opennebula.org/feed/" nil nil nil)
   ("Pydio" "http://pyd.io/feed/" nil nil nil)
   ("Google Chrome releases" "http://feeds.feedburner.com/GoogleChromeReleases" nil nil nil)
   ("Google Apps blog" "http://feeds.feedburner.com/GoogleAppsUpdates" nil nil nil)
   ("Ceph" "http://ceph.com/feed/" nil nil nil)
   ("Google apps status" "http://www.google.com/appsstatus/rss/en" nil nil nil)
   ;;; reddit
   ("Reddit front page" "https://www.reddit.com/.rss?feed=972d9ebd4046beab6e59c71d9b448f5977f4134e&user=perlstalker" nil nil nil)
   ("Reddit inbox" "https://www.reddit.com/message/inbox/.rss?feed=972d9ebd4046beab6e59c71d9b448f5977f4134e&user=perlstalker" nil nil nil)
     )))
