(el-get 'sync "pianobar")
;(set-variable 'pianobar-command "/usr/bin/pianobar")
;(set-variable 'pianobar-program-command "/usr/bin/pianobar")
(setq pianobar-username "perlstalker@gmail.com")
;(autoload 'pianobar "pianobar" nil t)
(global-set-key "\C-c+" 'pianobar-love-current-song)
(global-set-key "\C-c-" 'pianobar-ban-current-song)

(setq pianobar-key (kbd "<f7>"))
;(setq pianobar-key (kbd "\C-c r"))
(pianobar-key-setup)
